[2023-03-24T20:07:37.718+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator.log_sql_query manual__2023-03-24T20:07:35.709045+00:00 [queued]>
[2023-03-24T20:07:37.727+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator.log_sql_query manual__2023-03-24T20:07:35.709045+00:00 [queued]>
[2023-03-24T20:07:37.728+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-24T20:07:37.728+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-24T20:07:37.728+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-24T20:07:37.751+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): log_sql_query> on 2023-03-24 20:07:35.709045+00:00
[2023-03-24T20:07:37.755+0000] {standard_task_runner.py:55} INFO - Started process 662 to run task
[2023-03-24T20:07:37.758+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator', 'log_sql_query', 'manual__2023-03-24T20:07:35.709045+00:00', '--job-id', '17', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_python_operator.py', '--cfg-path', '/tmp/tmp1nh9ajjb']
[2023-03-24T20:07:37.758+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask log_sql_query
[2023-03-24T20:07:37.825+0000] {task_command.py:388} INFO - Running <TaskInstance: example_python_operator.log_sql_query manual__2023-03-24T20:07:35.709045+00:00 [running]> on host e7c16d9fd17d
[2023-03-24T20:07:37.860+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'log_sql_query', field 'templates_dict'. Template: {'query': 'sql/sample.sql'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/sample.sql
[2023-03-24T20:07:37.862+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 678, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/sample.sql
[2023-03-24T20:07:37.873+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=example_python_operator, task_id=log_sql_query, execution_date=20230324T200735, start_date=20230324T200737, end_date=20230324T200737
[2023-03-24T20:07:37.888+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task log_sql_query (sql/sample.sql; 662)
[2023-03-24T20:07:37.929+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-24T20:07:37.969+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
